#!/bin/bash

#
# Copyright 2014 by Amin Abbaspour
#
# This file is part of Urmia.io
#
# Urmia.io is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Urmia.io is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Urmia.io.  If not, see <http://www.gnu.org/licenses/>.
#

set -euo pipefail

function usage() {
    cat <<END >&2
USAGE: mput [OPTIONS] path
        -f  file        # file
        -a  account     # account (defaults to MANTA_USER env variable)
        -u  URL         # URL (defaults to MANTA_URL env variable)
        -h|?            # usage
        -v              # verbose

eg,
     mput -f sample.txt -u http://localhost:8085 /tck/stor/sample.txt
END
    exit $1
}

declare vrb=''

declare opt_file=''
declare opt_path=''
declare opt_url=${MANTA_URL}
declare opt_account=${MANTA_USER}

while getopts "f:u:a:hv" opt
do
    case ${opt} in
        f) opt_file=${OPTARG};;
        u) opt_url=${OPTARG};;
        a) opt_account=${OPTARG};;
        h) usage 0;;
        v) vrb=1;;
    esac
done

shift $(( OPTIND-1 ))
[ $# -gt 0 ] || { echo >&2 "path is mandatory"; usage 1; }

opt_path=$1

[ -z "$opt_file" ] && { echo >&2 "input file is mandatory"; usage 1; }
[ -e "$opt_file" ] || { echo >&2 "input file does not exist: $opt_file"; exit 2; }
[ -f "$opt_file" ] || { echo >&2 "input is not a file: $opt_file"; exit 3; }

declare -r cURL=$(which curl)
[ $? -eq 0 ] || { echo "cURL not found in path"; exit 4; }

declare filename=$(basename ${opt_file})

declare -r url="$opt_url$opt_path/$filename"

[ -z ${vrb} ] || {
    echo -e "file:\t$opt_file"
    echo -e "URL :\t$opt_url"
    echo -e "path:\t$opt_path"
    echo -e "account:\t$opt_account"
    echo -e "cURL:\t$cURL"
    echo -e "Target:\t$url"
}

${cURL} -# --progress-bar -i -X PUT -d @"$opt_file" ${url}