/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_urmia_dd_DirectDigest */

#ifndef _Included_io_urmia_dd_DirectDigest
#define _Included_io_urmia_dd_DirectDigest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_urmia_dd_DirectDigest
 * Method:    md5_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_urmia_dd_DirectDigest_md5_1init
  (JNIEnv *, jclass);

/*
 * Class:     io_urmia_dd_DirectDigest
 * Method:    md5_update
 * Signature: (JLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_urmia_dd_DirectDigest_md5_1update__JLjava_nio_ByteBuffer_2
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     io_urmia_dd_DirectDigest
 * Method:    md5_update
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_io_urmia_dd_DirectDigest_md5_1update__J_3B
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     io_urmia_dd_DirectDigest
 * Method:    md5_final
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_urmia_dd_DirectDigest_md5_1final
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
