#!/bin/bash

echo "creating folders"

mkdir -p /var/log/urmia
chown -R urmia:urmia /var/log/urmia

mkdir -p /var/run/urmia
chown -R urmia:urmia /var/run/urmia

echo "installing service"
/bin/systemctl -q enable urmia-obj-store.service

exit 0

