#!/bin/bash

echo "creating folders"

mkdir -p /var/log/urmia
chown -R urmia:urmia /var/log/urmia

mkdir -p /var/run/urmia
chown -R urmia:urmia /var/run/urmia

echo "installing obj api service"
/bin/systemctl -q enable urmia-obj-api.service

exit 0

